# Docker kubernetes config
# Article:
# https://maksood.medium.com/deploy-a-react-app-on-kubernetes-using-docker-129a75b79d58
apiVersion: apps/v1
kind: Deployment
metadata:
    name: punxy-docker
    labels:
        app: punxy-docker
spec:
    selector:
        matchLabels:
            app: punxy-docker
    replicas: 2
    template:
        metadata:
            labels:
                app: punxy-docker
        spec:
            containers:
            - name: punxy-docker
              image: kitajchuk/punxy-docker
              ports:
              - containerPort: 80
              resources:
                  limits:
                      memory: '128Mi'
                      cpu: '200m'
              livenessProbe:
                  httpGet:
                      path: /index.html
                      port: 80
                  initialDelaySeconds: 15
                  timeoutSeconds: 2
                  periodSeconds: 5
                  failureThreshold: 1
              readinessProbe:
                  httpGet:
                      path: /index.html
                      port: 80
                  initialDelaySeconds: 15
                  periodSeconds: 5
                  failureThreshold: 1