version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.22

jobs:
    aws-cli-setup:
        executor: aws-cli/default
        steps:
          - checkout
          - aws-cli/setup:
              profile-name: default
          - run: echo "Run your code here"
    build:
        working_directory: ~/punxy
        machine:
            enabled: true
        steps:
            - checkout
             - run:
                name: yarn install
                command: yarn install
            - run:
                name: yarn build
                command: yarn build
            - persist_to_workspace:
                root: ~/punxy
                paths:
                    - .
    deploy:
        working_directory: ~/punxy
        machine:
            enabled: true
        steps:
            - attach_workspace:
                at: ~/punxy
            - run:
                name: yarn deploy-s3
                command: yarn deploy-s3

workflows:
    version: 2
    build-deploy:
        jobs:
            - aws-cli-setup:
                context: aws
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: master
