name: github

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    environment: Production
    # Available tools on this machine:
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node Cache
        id: node-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
      - name: Install node_modules
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Lint, Test and Build
        run: yarn build
      - name: Configure AWS CLI
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy Production
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          aws s3 sync build ${{ secrets.S3_BUCKET }} --delete
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths '/*'
